### PR TITLE
Fix Syntax Error unexpected '{'

### PR DESCRIPTION
**Pull request by supatk**
Ref : https://github.com/plataformatec/devise/issues/4630

### CODE REVIEW

**Comment by damianlegawiec** [comment]
Thanks @supatk 👍

**Comment by MateoLa** [comment]
Same issue. 
Does the change to devise 4.4.0 work? Thanks, Mateo.

**Comment by vernondegoede** [comment]
@damianlegawiec Any indication when this fix will be pushed to Rubygems? The latest version is 3.3.1, which still refers to the incorrect Devise version.

**Comment by bbonislawski** [comment]
@vernondegoede we'll release it as soon as possible. Probably this week it will be done 👍

**Comment by vernondegoede** [comment]
Cool! Thanks for the insane fast reply. Cheers 🎉

**Pull request merged**
