### PR TITLE
Spree version compare

### PR DESCRIPTION
**Pull request by biagidp**
Added a method to compare spree versions. Fixes a bug resulting from using a string comparison on "2.1.11" > "2.1.3" returning false.

### CODE REVIEW

**Comment by JDutil** [comment]
I don't understand the purpose of this.

**Comment by biagidp** [comment]
In 2-1-stable the Coree::UserAddress module, which allows for saving addresses, isn't pulled in unless the Spree.version > "2.1.3" == true. This comparison fails for versions greater than "2.1.9" as a string comparison returns false for "2.1.10" > "2.1.3".

**Comment by JDutil** [comment]
I think we should just remove the conditional altogether...

**Comment by biagidp** [comment]
I didn't want to make any assumptions or break the code for anyone else. I'm happy to resubmit with the condition removed though.

**Comment by JDutil** [comment]
Well I'm thinking anyone using branch 2-1-stable would be using greater than version 2.1.3 so I think the conditional is fine to remove unless I'm missing something.

**Comment by mvz** [comment]
You could add a condition to require at least 2.1.3 in the gemspec.

**Comment by JDutil** [comment]
Fixed w/ https://github.com/spree/spree_auth_devise/commit/632d03afb67bfa7a33a0fb34e60252aa6df32ac5

**Pull request closed without merging**
