### PR TITLE
adds the missing translation for user_sessions.already_signed_out

### PR DESCRIPTION
**Pull request by QuintinAdam**

### CODE REVIEW

**Comment by QuintinAdam** [comment]
I'm pretty sure my one local addition didn't break the tests.

**Comment by JDutil** [comment]
The translation key doesn't match what the translation is saying.  Either the key being used is wrong or the message doesn't make sense.  Where do you see the message?

**Comment by QuintinAdam** [comment]
The key is used when you hit the `/logout` path when you are already signed out you. The message I added for the key is based off of the default devise message. https://github.com/plataformatec/devise/blob/master/config/locales/en.yml#L46 The message could be changed to 'You are already signed out'.

**Comment by JDutil** [comment]
Shouldn't this fall back to devise translations though?  I've been meaning to just remove the devise translations altogether since they just duplicate devises

**Comment by QuintinAdam** [comment]
Currently it is not falling back to the Devise translation. 

Do you want help removing the translations? I would be happy to work on that.

**Comment by JDutil** [comment]
I wonder why it doesn't fallback to devise.. Is it because we have a devise key at:
https://github.com/spree/spree_auth_devise/pull/262/files#diff-37c9b835927e3c363588f172de9bb6faR5

That'd be great if you want to just remove the devise entries so we can just rely on their defaults.

**Comment by QuintinAdam** [comment]
I found out that Spree also has devise translations.  So it was looking for `en.devise.user_sessions.spree_user.already_signed_out` here. https://github.com/spree/spree/blob/7d52bbf900a5b5b57c98f9a0d8c51cf8d92c1706/core/config/locales/en.yml#L356 just more duplicate devises translations.

So even if I remove the translations from spree_auth_devise the problems lives on Spree itself. 

I'll make a PR for Spree then to fix this issue and I'll continue to work on removing the translations from this app.

**Pull request closed without merging**
