### PR TITLE
Fix order association (2-4-stable)

### LINKED ISSUE #306: Fix for #6578 Breaks Carts for New Customers (Reopen #290)
Previous issue: #290 

The concerned issue is closed and I'm not sure if anyone is watching so I'm opening a new one to be sure :

Problem : 

Cart are not merged if when a user logs in. Previous guest_cart is not merged with the signed_in cart and the the guest_cart is in limbo since when you log out, guest_token gets destroyed

Steps :

1) Log in
2) Add item #2 to cart
3) Log out
4) Add item #1 to cart as a guest
5) Log in

Expected results :
Cart contain Item #1 and Item #2 since the carts should be merged

Results :

Guest cart is discarded so you only have Item #2 in your cart

Gemfile
https://gist.github.com/dangerdogz/5563861ca6a1d4d0649f

Gemfile.lock
https://gist.github.com/dangerdogz/bf19cf07bf569360afd8

Regression introduced in commit 336b0e4

Suggested solution :

The offending commit intend to fix the following problem :

1) Checkout as a guest
2) Checkout as a logged in user

The guest user ends up in the user account because since guest_token is cleared on logout, it's not resetted after the guest checkout and the logged in user reuse the same token thus associating both order to the user

In my opinion, it's somewhat an edge case since you have to do the steps on the same computer in the correct order and the fix ends breaking an essential checkout flow (shop, log in, countinue)

Thus, I suggest that we revert the offending commit and fix the original problem in one of the following ways :

1) Check the order status before the association so we avoid associating completed guest order from a previous session with other users (not sure about this solution)

```ruby
Warden::Manager.after_set_user except: :fetch do |user, auth, opts|
  if auth.cookies.signed[:guest_token].present?
    if user.is_a?(Spree::User)
      Spree::Order.where(email: user.email, guest_token: auth.cookies.signed[:guest_token], user_id: nil).each do |order|
        order.associate_user!(user) unless order.completed?
      end
    end
  end
end
```

2) We could destroy the guest_token after a successful guest checkout since the "guest session" is complete (no cart, order is done, no reason to maintain a guest session since it's only purpose is to shop and then checkout and it's useless after the process is completed)

I'll make the pull request once a solution is selected, feel free to chime in if you have a better way to fix it, I'm not that much familiar with this part of Spree

### PR DESCRIPTION
**Pull request by mvz**
Rebase of #332 on 2-4-stable. Resolves #306.

### CODE REVIEW

**Comment by Mafi88** [comment]
CircleCi and Travis specs are failing... could you please look into it?

**Comment by mvz** [comment]
@Mafi88 I'll take a look.

**Comment by mvz** [comment]
@Mafi88 it looks like 2-4-stable's build is itself broken: https://travis-ci.org/spree/spree_auth_devise/builds/116355413. I'm having a go at fixing it in #335.

**Comment by mvz** [comment]
@Mafi88 I have no idea why the CircleCI build started succeeding, but #335 fixes the 2-4-stable build. Once that's merged, I can rebase this PR and the build should succeed.

**Comment by damianlegawiec** [comment]
Thanks @mvz !

**Pull request merged**
